// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadXMCGSockProg returns the embedded CollectionSpec for XMCGSockProg.
func LoadXMCGSockProg() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_XMCGSockProgBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load XMCGSockProg: %w", err)
	}

	return spec, err
}

// LoadXMCGSockProgObjects loads XMCGSockProg and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*XMCGSockProgObjects
//	*XMCGSockProgPrograms
//	*XMCGSockProgMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadXMCGSockProgObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadXMCGSockProg()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// XMCGSockProgSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XMCGSockProgSpecs struct {
	XMCGSockProgProgramSpecs
	XMCGSockProgMapSpecs
	XMCGSockProgVariableSpecs
}

// XMCGSockProgProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XMCGSockProgProgramSpecs struct {
	XmSockProg1 *ebpf.ProgramSpec `ebpf:"xm_sock_prog1"`
	XmSockProg2 *ebpf.ProgramSpec `ebpf:"xm_sock_prog2"`
}

// XMCGSockProgMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XMCGSockProgMapSpecs struct {
}

// XMCGSockProgVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XMCGSockProgVariableSpecs struct {
}

// XMCGSockProgObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadXMCGSockProgObjects or ebpf.CollectionSpec.LoadAndAssign.
type XMCGSockProgObjects struct {
	XMCGSockProgPrograms
	XMCGSockProgMaps
	XMCGSockProgVariables
}

func (o *XMCGSockProgObjects) Close() error {
	return _XMCGSockProgClose(
		&o.XMCGSockProgPrograms,
		&o.XMCGSockProgMaps,
	)
}

// XMCGSockProgMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadXMCGSockProgObjects or ebpf.CollectionSpec.LoadAndAssign.
type XMCGSockProgMaps struct {
}

func (m *XMCGSockProgMaps) Close() error {
	return _XMCGSockProgClose()
}

// XMCGSockProgVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadXMCGSockProgObjects or ebpf.CollectionSpec.LoadAndAssign.
type XMCGSockProgVariables struct {
}

// XMCGSockProgPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadXMCGSockProgObjects or ebpf.CollectionSpec.LoadAndAssign.
type XMCGSockProgPrograms struct {
	XmSockProg1 *ebpf.Program `ebpf:"xm_sock_prog1"`
	XmSockProg2 *ebpf.Program `ebpf:"xm_sock_prog2"`
}

func (p *XMCGSockProgPrograms) Close() error {
	return _XMCGSockProgClose(
		p.XmSockProg1,
		p.XmSockProg2,
	)
}

func _XMCGSockProgClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed xmcgsockprog_bpfel.o
var _XMCGSockProgBytes []byte
